Finished common function
RNNLA/Scrapper pull request #7
Opened 2023-08-08 13:35 UTC by hsmint

Finished common function without multiprocessing

2023-08-09 06:27 UTC, AntsThatWander approved these changes
LGTM

2023-08-09 08:08 UTC, talisman6803 commented
LGTM

2023-08-09 08:08 UTC, dart-bird requested changes
`parse.py` 52 line 참고

2023-08-09 08:08 UTC, dart-bird commented on src/parse.py
> +        data = soup.select(tag)
Content selector 는 article body 하나밖에 없습니다.
`data = soup.select_one(tag).get_text()` 코드로 해야합니다.

2023-08-09 08:10 UTC, talisman6803 approved these changes
LGTM

2023-08-10 13:11 UTC, dart-bird approved these changes

2023-08-10 13:12 UTC, merged